#!/bin/bash

program=./program
testcase=./testcase
TIMESTAMP=$(date +"%Y%m%d-%H%M%S-%N")
code=main
RED="\e[31m"
BLINK="\e[5m"
GREEN="\e[32m"
RESET="\e[0m"
BGFILL="\e[7m"
while getopts ":p:t:c:" opt; do
  case $opt in
    p) program="$OPTARG" # testing program
    ;;
    t) testcase="$OPTARG" # testcase folder
    ;;
    c) code="$OPTARG" # source program
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done
echo $program
# compile program
if $(make run code=$code output=$program);
then
  echo -e $GREEN"Compile Success"$RESET
else
  echo -e $RED"Compile Failed!"$RESET
fi

#if [ -f "./program" ]; then
#  echo -e "$BLINK$GREEN@Compile success!$RESET"
#fi
final="success" # AC
part="false"
for c in $testcase/*.in; do
  bcase=`basename $c .in`
  echo "_____________ $bcase ______________"
  echo "------------Your output:----------"
  echo -e '\e[33m'
  $program < $c > __testcase
  testout=`cat __testcase`
  #testout=`$program < $c` # > __testcase
  cat __testcase
  #echo $testout
  #echo $testout > __testcase
  echo -e $RESET
  gout=`basename $(md5sum $testcase/$bcase.out)` # good output
  uout=`basename $(md5sum __testcase)` # your output
  if [ "$gout" = "$uout" ];
  then
    echo ""
    echo -e "$GREEN   $bcase's Answer is correct! $RESET"
    echo "----------------------------------"
    echo ""
    part="true"
  else
    
    echo "------------Real Output:----------"
    cat $testcase/$bcase.out
    echo "----------------------------------"
    echo ""
    echo -e "$RED       Wrong Answer! $RESET"
    final="failed"
  fi
  echo "===================================="
done

rm -f __testcase # remove test output file

echo -e $BLINK$BGFILL
if [ "$final" = "success" ];
then
  echo -e "$GREEN"
  echo "                                    "
  echo "        Alternating  Current        "
  echo "                                    "
  BAK=AC_$TIMESTAMP
elif [ "$part" = "true" ];
then 
  echo -e "\e[33m"
  echo "                                    "
  echo "         Partially  Correct         "
  echo "                                    "
  BAK=PA_$TIMESTAMP
else
  echo -e "$RED"
  echo "                                    "
  echo "            Wrong Answer            "
  echo "                                    "
  BAK=WA_$TIMESTAMP
fi
echo -e $RESET

# auto backup
make bak BAKNAME=$BAK > /dev/null
# running test case



